site_name: a n notes
site_description: a n notes description
copyright: 2022 aniewoehner
repo_name: aniewoehner/notes
repo_url: https://github.com/aniewoehner/notes
edit_uri: edit/main/docs/
docs_dir: ./docs
site_dir: ./site

theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  shortcuts:
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  language: en
  include_search_page: true
  search_index_only: true
  features:
    - navigation.instant
    - search.share
    - search.highlight
    - search.suggest
  font:
    text: Noto Sans
    code: IMB Plex Mono

plugins:
  - search:
      separator: '[\s\-\.]+'
      prebuild_index: python
      lang:
        - en
  - minify:
      minify_html: true
  - roamlinks

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/aniewoehner
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/aniewoehner

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css
